import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { increment, decrement, getCount } from "../Blockchain";
const Home: NextPage = () => {
  const [count, setCount] = useState(0);
  // const obtainCount = async () => {
  //   const res = await getCount();
  //   console.log(res);
  //   const resInInt = parseInt(res, 10);
  //   console.log(resInInt);
  //   setCount(resInInt);
  // };

  // const increase = async () => {
  //   const res = await increment();
  //   console.log(res);
  //   await obtainCount();
  // };
  // const decrease = async () => {
  //   const res = await decrement();
  //   console.log(res);
  //   await obtainCount();
  // };
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button
          style={{
            background: "green",
            padding: "5px",
            color: "white",
            fontSize: "25px",
            borderRadius: "10px",
            marginBottom: "20px",
            marginTop: "20px",
          }}
        >
          increment
        </button>
        <button
          style={{
            background: "red",
            padding: "5px",
            color: "white",
            fontSize: "25px",
            borderRadius: "10px",
            marginBottom: "20px",
          }}
        >
          Decrement
        </button>
        <button
          style={{
            background: "blue",
            padding: "5px",
            color: "white",
            fontSize: "25px",
            borderRadius: "10px",
          }}
        >
          Get Count
        </button>{" "}
        <p
          style={{
            fontSize: "30px",
          }}
        >
          {" "}
          count value
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
